version: "3.8"

services:
  build:
    image: gcc:latest
    volumes:
      - .:/var/app
    command: >
      bash -c "apt-get update &&
               apt-get install -y cmake &&
               mkdir -p /var/app/build &&
               cd /var/app/build &&
               cmake ../src/Program &&
               make"

  run:
    image: gcc:latest
    depends_on:
      - build
    volumes:
      - .:/var/app
    command: /var/app/build/bin/main /var/app/input/dc_battles.csv
