version: "3.8"

services:
  build:
    image: arm-cross-compile
    volumes:
      - .:/var/app
    command: >
      bash -c "mkdir -p /var/app/build &&
               cd /var/app/build &&
               cmake -DCMAKE_TOOLCHAIN_FILE=/var/app/arm-toolchain.cmake ../src/Program &&
               make"

  run:
    image: arm-cross-compile
    depends_on:
      - build
    volumes:
      - .:/var/app
    command: qemu-arm /var/app/build/bin/main
