name: ARM Cross-Compile with CMake

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      ACTIONS_ALLOW_USE_UNSECURE_NODE_VERSION: true
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install ARM Cross-Compilation Tools and patchelf
        run: |
          sudo apt-get update
          sudo apt-get install -y gcc-arm-linux-gnueabi g++-arm-linux-gnueabi qemu-user-static patchelf

      - name: Create build directory
        run: mkdir -p arm-build

      - name: Run CMake with ARM toolchain
        working-directory: arm-build
        run: cmake -DCMAKE_TOOLCHAIN_FILE=../arm-toolchain.cmake ..

      - name: Build
        working-directory: arm-build
        run: make

      - name: Fix Binary Interpreter Path using patchelf
        working-directory: arm-build
        run: patchelf --set-interpreter /usr/arm-linux-gnueabi/lib/ld-linux.so.3 ./bin/main

      - name: Run Program with QEMU
        working-directory: arm-build
        run: qemu-arm-static ./bin/main ../input/dc_battles.csv
