name: Code Coverage

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  coverage:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y gcc gcovr ruby ruby-dev
        sudo gem install ceedling

    - name: Run Ceedling and Generate Coverage Report
      run: |
        ceedling clobber gcov:all
        gcovr -r . --html --html-details -o ./gcovr-report.html

    - name: Zip Coverage Report
      run: |
        zip coverage_reports.zip ./gcovr-report.html
        find . -maxdepth 1 -name "gcovr-report.*.html" -exec zip coverage_reports.zip {} +

    - name: Upload Coverage Report
      uses: actions/upload-artifact@v2
      with:
        name: coverage-report
        path: coverage_reports.zip
